"""Add date_sent and read columns to Message model

Revision ID: 41d5e3a9375c
Revises: f9125b011624
Create Date: 2025-10-04 16:43:16.664969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41d5e3a9375c'
down_revision = 'f9125b011624'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_sent', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('read', sa.Boolean(), nullable=True))
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=False))
        batch_op.drop_column('read')
        batch_op.drop_column('date_sent')

    # ### end Alembic commands ###
